name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: compile
      run: dotnet build ./src/*.csproj --configuration Release
    - name: test
      run: dotnet test ./test/*.csproj
    - name: package
      run: dotnet pack ./src/*.csproj
