name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
     #   source-url: https://nuget.pkg.github.com/aaronlcope/index.json
     # env:
     #   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: compile
      run: dotnet build ./src/*.csproj --configuration Release
    
    - name: test
      run: dotnet test ./test/*.csproj
    
    - name: package
      run: dotnet pack ./src/*.csproj --configuration Release
    
    - name: push
      env: 
        NUGET_AUTH_TOKEN: ${{secrets.PACKAGE}}
      run: dotnet nuget push -s https://nuget.pkg.github.com/aaronlcope -k $GITHUB_TOKEN ./src/**/*/*.nupkg --skip-duplicate
        
