name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.101
        
    - name: compile
      run: dotnet build ./src/*.csproj --configuration Release
    
    - name: test
      run: dotnet test ./test/*.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./
    
    # - name: prepare quality analysis with project version
    #  run: | 
    #    CSPROJ_FILE=src/dependency.csproj
    #    V=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)') $CSPROJ_FILE
    #    sed -i -e "s/x.y.z/$V/g" src/sonar-project.properties
    #    cat src/sonar-project.properties
      
    # - name: quality analysis
    #  uses: SonarSource/sonarcloud-github-action@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: dotnet-sonarscanner
      uses: Secbyte/dotnet-sonarscanner@2.1
      with:
        buildCommand: dotnet build ./src/*.csproj
        testCommand: dotnet test ./test/*.csproj
        projectKey: aaronlcope_dependency
        projectName: dependency
        sonarOrganisation: aaronlcope
        beginArguments: /d:sonar.verbose="true" /d:sonar.cs.opencover.reportsPaths="/path/to/coverage.xml" /d:sonar.coverage.exclusions="**/*.cs"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: package
      run: dotnet pack ./src/*.csproj --configuration Release
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@master
    
    - name: where is nuget?
      run: which nuget
      
    - name: add nuget source
      run: nuget sources Add -Name "github" -Source "https://nuget.pkg.github.com/aaronlcope/index.json" -Username "aaroncope@gmail.com" -Password ${{secrets.GITHUB_TOKEN}}
      
    - name: push
      run: nuget push -Source "github" ./src/**/*/*.nupkg -SkipDuplicate
