name: ci

on: 
  push:
    branches: 
    - master # Only fire for commits on master branch
    pull_request:
    - types: [opened, edited] # Only fire for opened and edited pull requests.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.102
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@master

    - name: run ci
      run: |
      sonar_host_url="https://sonarcloud.io"
      sonar_organization_name=${github_repository_key%%/*} # retain the part before the last slash 
      sonar_project_name=${github_repository_key##*/}  # retain the part after the last slash 
      ./scripts/ci.sh -u "$sonar_host_url" -t "${{ secrets.SONAR_TOKEN }}" -o "$sonar_organization_name" -k "$sonar_project_key" -n "$sonar_project_name" -b "master"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}